name: flutter_expanded_tile
description: An Expansion tile similar to the list tile supports leading widget,and programatic control with content expansion animation.
version: 0.3.7
homepage: https://github.com/micazi/flutter_expanded_tile

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
